#!/bin/bash
cd "$(dirname "$(realpath "$0")")" || exit
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions
#------------------------------------------------------------------------------

BASE_CASE_PATH="$(realpath !baseCase!)"
for p in $BASE_CASE_PATH/processor*/; do
    ln -s $p 
done

#------------------------------------------------------------------------------
